[package]
name = "chainpass"
version = "0.1.0"
edition = "2021"

[lib]
name = "chainpass"
path = "src/lib.rs"

[[bin]]
name = "chainpass"
path = "src/main.rs"


[dependencies]
anyhow = "1.0.90"
bdk = "0.29.0"
bitcoin = "0.32.3"
